#!/usr/bin/env bash

docker run --privileged --rm -v /dev:/dev:ro -v "$PWD/src":/src -v "$PWD/img":/img -w /src \
    -e ALPINE_MIRROR="http://dl-cdn.alpinelinux.org/alpine" \
    -e ALPINE_VERSION=3.10.3 \
    -e ARCH=aarch64 \
    -e KERNEL_REPO="https://github.com/raspberrypi/firmware" \
    -e KERNEL_BUILD_DIR=/img/rpi-kernel \
    -e ROOT_PASSWORD=${ROOT_PASSWORD} \
    -e CACHE_DIR=/img/cache \
    alpine ./make-image

#    -e KERNEL_BUILD_DIR=/img/rpi-kernel \
#    -e KERNEL_VERSION=4.19.88-v8+ \
